#!/usr/bin/env bash

set -e

if [ ! -f /build/PKGBUILD ]; then
  echo -e "The folder /build must countain the PKGBUILD file."
  exit 1
fi

cd /build
chown -R makepkg:users /build

sudo -u makepkg makepkg --noconfirm -s

mv $package*.pkg.tar.xz /pkg
